name: Pull Request
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Restore cache
        id: restore-cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install
        if: steps.restore-cache.outputs.cache-hit != 'true'
        working-directory: packages/core
        run: npm i

      - name: Test
        working-directory: packages/core
        run: npm run test
